spring.application.name=connect-me

spring.datasource.url=jdbc:h2:mem:connectme
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

jwt.secret=YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY=
jwt.access-token-expiry=3600000
jwt.refresh-token-expiry=604800000

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false